apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app: ai-api-gateway
data:
  MINIO_ENDPOINT: "<end-point>:80"
  MINIO_BUCKET_NAME: "ai-media"
  MINIO_SECURE: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    app: ai-api-gateway
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "<ACCESS_KEY>"
  MINIO_SECRET_KEY: "<SECRET_KEY>"
